# Generated by Django 4.1.5 on 2023-01-15 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_event', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('poster', models.ImageField(upload_to='poster/%Y')),
                ('tech_info', models.FileField(blank=True, null=True, upload_to='tech_files/%Y')),
                ('result', models.URLField(blank=True, db_index=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('registration_deadline', models.DateTimeField(null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password1', models.CharField(max_length=50)),
                ('password2', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(choices=[('м21А', 'М21А'), ('м21Е', 'М21Е'), ('ж21А', 'Ж21А'), ('ж21Е', 'Ж21Е')], max_length=4)),
                ('chip', models.CharField(choices=[('y', 'Да, у меня нет своего чипа'), ('n', 'Нет, я возьму свой чип')], max_length=1)),
                ('num_chip', models.CharField(max_length=10)),
                ('agree', models.BooleanField(null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.events')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.user')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='participants',
            field=models.ManyToManyField(blank=True, to='events.user'),
        ),
    ]
