# Generated by Django 4.1.5 on 2023-01-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='num_chip',
            field=models.CharField(max_length=10),
        ),
    ]
